site_name: Zahra Khodakarami
site_description: Research and projects
site_url: https://Zkhodakarami.github.io
repo_url: https://github.com/Zkhodakarami/Zkhodakarami.github.io
theme:
  name: null
  custom_dir: 'cinder'

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Work Experience: work.md
  - Leadership & Mentorship: talks.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - attr_list
  - def_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Zkhodakarami
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/khodakarami
      name: LinkedIn
    - icon: simple/googlescholar
      link: https://scholar.google.com/citations?user=aXrProgAAAAJ&hl=en
      name: Google Scholar
    - icon: fontawesome/brands/twitter
      link: https://x.com/khodakaramim
      name: X
  meta:
    - name: description
      content: Research and projects by Zahra Khodakarami
    - property: og:title
      content: Zahra Khodakarami
    - property: og:description
      content: Research and projects
    - property: og:type
      content: website
    - property: og:url
      content: https://Zkhodakarami.github.io
    - property: og:image
      content: /assets/social-card.svg
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: Zahra Khodakarami
    - name: twitter:description
      content: Research and projects
    - name: twitter:image
      content: /assets/social-card.svg

extra_css:
  - assets/overrides.css

plugins:
  - search
